<?php

/**
 * @file
 * Contains mass_times.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mass_times_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mass_times module.
    case 'help.page.mass_times':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mass Times') . '</p>';
      return $output;

    default:
  }
}

function mass_times_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Make name field longer.
  if ($form_id == 'directory_parishes_add_form' || $form_id == 'directory_parishes_edit_form') {
    $form['name']['widget'][0]['value']['#maxlength'] = 255;
  }
}
